baseurl                  = "https://waynedupreez1.github.io/AkadupTinker/"           # Your domain name
publishDir               = "docs"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Akadup Tinker Site"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = ""
    homepage             = "main"                           # What to call the home page link
    footerText           = ""

# Metadata for Open Graph and Twitter
    description          = "The site with Tinker projects"               # Max 160 characters show in search results
    images               = [""]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "AkadupTinker"
    # rss                = ""

[[params.mainMenu]]
    link = "posts"
    text = "Posts"

[[params.mainMenu]]
    link = "gallery"
    text = "Gallery"

[[params.mainMenu]]
    link = "about"
    text = "Wayne who?"

[imaging]
    quality = 75
